name: Format with Prettier

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/prettier.yml"
      - "**.php"
      - "**.md"
      - "**.js"
      - "**.css"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout Push
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3

      - name: Install prettier and plugin-php
        run: npm install --global prettier@2.8.1 @prettier/plugin-php@0.18.9

      - name: Check formatting with Prettier
        continue-on-error: true
        run: composer format:check 

      - name: Prettify code
        run: |
          composer format 
          git diff

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "style: Formatted code with Prettier"
          default_author: github_actions
